# Generated by Django 5.1.15 on 2026-06-05 12:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendance_date', models.DateField(db_index=True)),
                ('punch_in_time', models.DateTimeField(blank=True, null=True)),
                ('punch_out_time', models.DateTimeField(blank=True, null=True)),
                ('punch_in_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('punch_in_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('punch_out_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('punch_out_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('working_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'attendance',
                'ordering': ['-attendance_date', '-punch_in_time'],
                'indexes': [models.Index(fields=['attendance_date'], name='attendance_attenda_45664f_idx'), models.Index(fields=['user', 'attendance_date'], name='attendance_user_id_44443d_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'attendance_date'), name='unique_attendance_per_user_per_day')],
            },
        ),
    ]
