# Generated by Django 5.1.15 on 2026-06-05 12:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('ATTENDANCE_CREATED', 'Attendance Created'), ('PUNCH_IN_RECORDED', 'Punch In Recorded'), ('PUNCH_OUT_RECORDED', 'Punch Out Recorded'), ('CORRECTION_REQUESTED', 'Correction Requested'), ('CORRECTION_APPROVED', 'Correction Approved'), ('CORRECTION_REJECTED', 'Correction Rejected')], db_index=True, max_length=50)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='attendance.attendance')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'attendance_activities',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['attendance', 'created_at'], name='attendance__attenda_9c9e84_idx')],
            },
        ),
        migrations.CreateModel(
            name='AttendanceCorrectionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('correction_type', models.CharField(choices=[('ACCIDENTAL_PUNCH_OUT', 'Accidental Punch Out'), ('MISSED_PUNCH_OUT', 'Missed Punch Out'), ('INCORRECT_TIME', 'Incorrect Time'), ('GPS_ISSUE', 'GPS Issue'), ('OTHER', 'Other')], db_index=True, max_length=50)),
                ('requested_punch_in_time', models.DateTimeField(blank=True, null=True)),
                ('requested_punch_out_time', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_attendance_corrections', to=settings.AUTH_USER_MODEL)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correction_requests', to='attendance.attendance')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_correction_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'attendance_correction_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='attendance__status_e30fad_idx'), models.Index(fields=['requested_by', 'status'], name='attendance__request_2984d6_idx')],
            },
        ),
    ]
