# Generated by Django 5.1.15 on 2026-06-16 05:03

import apps.pricing.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0011_followup_stage_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RESPONDED', 'Responded')], db_index=True, default='PENDING', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('submission_mode', models.CharField(blank=True, choices=[('VENDOR_UPLOAD', 'Vendor Upload'), ('MANUAL_PRICING', 'Manual Pricing')], max_length=20)),
                ('response_remarks', models.TextField(blank=True)),
                ('vendor_quote_pdf', models.FileField(blank=True, upload_to=apps.pricing.models.pricing_vendor_upload_path)),
                ('generated_quotation_pdf', models.FileField(blank=True, upload_to=apps.pricing.models.pricing_quotation_upload_path)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_requests', to='leads.lead')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pricing_requests_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pricing_requests',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='PricingResponseLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('lead_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_responses', to='leads.leaditem')),
                ('pricing_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='pricing.pricingrequest')),
            ],
            options={
                'db_table': 'pricing_response_line_items',
                'ordering': ['lead_item__created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='pricingrequest',
            index=models.Index(fields=['lead'], name='pricing_req_lead_id_090b86_idx'),
        ),
        migrations.AddIndex(
            model_name='pricingrequest',
            index=models.Index(fields=['status', 'requested_at'], name='pricing_req_status_0b5100_idx'),
        ),
        migrations.AddConstraint(
            model_name='pricingresponselineitem',
            constraint=models.UniqueConstraint(fields=('pricing_request', 'lead_item'), name='unique_pricing_line_per_request'),
        ),
    ]
