# Generated by Django 5.1.15 on 2026-07-22 11:39

import apps.expenses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='expense',
            new_name='expenses_submitt_ed1890_idx',
            old_name='expenses_submitt_0f0f0f_idx',
        ),
        migrations.RenameIndex(
            model_name='expense',
            new_name='expenses_status_0e583e_idx',
            old_name='expenses_status__1a1a1a_idx',
        ),
        migrations.AlterField(
            model_name='expense',
            name='receipt',
            field=models.FileField(help_text='Receipt file is required for new expense submissions.', max_length=500, upload_to=apps.expenses.models.expense_receipt_upload_path),
        ),
    ]
