# Generated by Django 5.1.15 on 2026-06-04 06:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('sequence', models.PositiveIntegerField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'lead_stages',
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'product categories',
                'db_table': 'product_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('contact_person', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('estimated_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('lead_source', models.CharField(choices=[('WEBSITE', 'Website'), ('REFERRAL', 'Referral'), ('TENDER', 'Tender'), ('WHATSAPP', 'WhatsApp'), ('EMAIL', 'Email'), ('COLD_CALL', 'Cold Call'), ('EXISTING_CUSTOMER', 'Existing Customer'), ('WALK_IN', 'Walk-In'), ('OTHER', 'Other')], default='OTHER', max_length=100)),
                ('next_followup_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='leads.leadstage')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='leads.productcategory')),
            ],
            options={
                'db_table': 'leads',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['assigned_to'], name='leads_assigne_c5180e_idx'), models.Index(fields=['stage'], name='leads_stage_i_8bd381_idx'), models.Index(fields=['category'], name='leads_categor_526297_idx'), models.Index(fields=['next_followup_date'], name='leads_next_fo_05c9a4_idx'), models.Index(fields=['is_active'], name='leads_is_acti_3fb413_idx')],
            },
        ),
    ]
