# Generated by Django 5.1.15 on 2026-06-10 07:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_remove_lead_lead_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('followup_date', models.DateField()),
                ('followup_type', models.CharField(choices=[('CALL', 'Call'), ('MEETING', 'Meeting'), ('SITE_VISIT', 'Site Visit'), ('EMAIL', 'Email'), ('TENDER_DISCUSSION', 'Tender Discussion')], default='CALL', max_length=30)),
                ('remarks', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lead_followups',
                'ordering': ['followup_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StageHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('old_stage', models.CharField(blank=True, max_length=100)),
                ('new_stage', models.CharField(max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'lead_stage_history',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='leaditem',
            new_name='lead_items_lead_id_34053a_idx',
            old_name='lead_items_lead_id_idx',
        ),
        migrations.RenameIndex(
            model_name='leaditem',
            new_name='lead_items_categor_5ce12a_idx',
            old_name='lead_items_category_idx',
        ),
        migrations.RenameIndex(
            model_name='leaditem',
            new_name='lead_items_product_a1e403_idx',
            old_name='lead_items_model_idx',
        ),
        migrations.AlterField(
            model_name='leaditem',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name='leaditem',
            index=models.Index(fields=['product'], name='lead_items_product_534e30_idx'),
        ),
        migrations.AddIndex(
            model_name='leaditem',
            index=models.Index(fields=['brand'], name='lead_items_brand_i_49f66f_idx'),
        ),
        migrations.AddField(
            model_name='followup',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_followups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='followup',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_followups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='followup',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='leads.lead'),
        ),
        migrations.AddField(
            model_name='stagehistory',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stagehistory',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_history', to='leads.lead'),
        ),
        migrations.AddIndex(
            model_name='followup',
            index=models.Index(fields=['lead'], name='lead_follow_lead_id_77c3af_idx'),
        ),
        migrations.AddIndex(
            model_name='followup',
            index=models.Index(fields=['assigned_to'], name='lead_follow_assigne_69b565_idx'),
        ),
        migrations.AddIndex(
            model_name='followup',
            index=models.Index(fields=['followup_date'], name='lead_follow_followu_00ef05_idx'),
        ),
        migrations.AddIndex(
            model_name='followup',
            index=models.Index(fields=['status', 'followup_date'], name='lead_follow_status_16dd87_idx'),
        ),
        migrations.AddIndex(
            model_name='stagehistory',
            index=models.Index(fields=['lead'], name='lead_stage__lead_id_737c44_idx'),
        ),
        migrations.AddIndex(
            model_name='stagehistory',
            index=models.Index(fields=['changed_at'], name='lead_stage__changed_6299dd_idx'),
        ),
    ]
