# Generated by Django 5.1.15 on 2026-06-25 12:05

import apps.leads.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0013_lead_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaddocument',
            name='file',
            field=models.FileField(max_length=500, upload_to=apps.leads.models.lead_document_upload_path),
        ),
    ]
