# Generated by Django 5.1.15 on 2026-06-25 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0014_lead_document_file_max_length'),
        ('leads', '0014_lead_gut_feeling_percent'),
    ]

    operations = [
    ]
