# Generated by Django 5.1.15 on 2026-07-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0015_merge_20260625_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='billed_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Revenue / billing amount (₹). Defaults to deal value when won if empty.', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='business_segment',
            field=models.CharField(choices=[('TRADING', 'Trading'), ('SOLUTIONS', 'Solutions')], db_index=True, default='TRADING', help_text='MBR Sales pack segment: Trading (PC/Laptop/etc.) or Solutions.', max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='competitor',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lead',
            name='deal_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Opportunity / order booking value (₹).', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='expected_close_date',
            field=models.DateField(blank=True, help_text='Expected close month/date for pipeline forecasting.', null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='gross_margin_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Gross margin amount (₹).', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='lost_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lead',
            name='recovery_action',
            field=models.TextField(blank=True),
        ),
    ]
