# Generated by Django 5.1.15 on 2026-06-04 06:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('LEAD_CREATED', 'Lead Created'), ('LEAD_UPDATED', 'Lead Updated'), ('STAGE_CHANGED', 'Stage Changed'), ('FOLLOWUP_UPDATED', 'Follow-up Updated'), ('NOTE_ADDED', 'Note Added'), ('LEAD_ASSIGNED', 'Lead Assigned'), ('LEAD_CLOSED_WON', 'Lead Closed Won'), ('LEAD_CLOSED_LOST', 'Lead Closed Lost')], max_length=100)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='leads.lead')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lead_activities',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['lead'], name='lead_activi_lead_id_1a18d6_idx'), models.Index(fields=['created_at'], name='lead_activi_created_6a3601_idx')],
            },
        ),
    ]
