# Generated by Django 5.1.15 on 2026-06-16 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leadactivity',
            options={'ordering': ['-created_at'], 'verbose_name': 'lead activity', 'verbose_name_plural': 'lead activities'},
        ),
        migrations.AlterField(
            model_name='leadactivity',
            name='activity_type',
            field=models.CharField(choices=[('LEAD_CREATED', 'Lead Created'), ('LEAD_UPDATED', 'Lead Updated'), ('STAGE_CHANGED', 'Stage Changed'), ('FOLLOWUP_UPDATED', 'Follow-up Updated'), ('NOTE_ADDED', 'Note Added'), ('LEAD_ASSIGNED', 'Lead Assigned'), ('LEAD_CLOSED_WON', 'Lead Closed Won'), ('LEAD_CLOSED_LOST', 'Lead Closed Lost'), ('PRICE_REQUESTED', 'Price Requested'), ('PRICING_RESPONSE_RECEIVED', 'Pricing Response Received'), ('VENDOR_QUOTE_UPLOADED', 'Vendor Quote Uploaded'), ('QUOTATION_GENERATED', 'Quotation Generated')], max_length=100),
        ),
    ]
