# Generated by Django 5.1.15 on 2026-07-22 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_alter_leadactivity_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadactivity',
            name='activity_type',
            field=models.CharField(choices=[('LEAD_CREATED', 'Lead Created'), ('LEAD_UPDATED', 'Lead Updated'), ('STAGE_CHANGED', 'Stage Changed'), ('FOLLOWUP_UPDATED', 'Follow-up Updated'), ('FOLLOWUP_SCHEDULED', 'Follow-up Scheduled'), ('FOLLOWUP_COMPLETED', 'Follow-up Completed'), ('NOTE_ADDED', 'Note Added'), ('LEAD_ASSIGNED', 'Lead Assigned'), ('LEAD_CLOSED_WON', 'Lead Closed Won'), ('LEAD_CLOSED_LOST', 'Lead Closed Lost'), ('PRICE_REQUESTED', 'Price Requested'), ('PRICING_RESPONSE_RECEIVED', 'Pricing Response Received'), ('VENDOR_QUOTE_UPLOADED', 'Vendor Quote Uploaded'), ('QUOTATION_GENERATED', 'Quotation Generated'), ('GUT_FEELING_UPDATED', 'Gut Feeling Updated'), ('EXPENSE_SUBMITTED', 'Expense Submitted'), ('EXPENSE_APPROVED', 'Expense Approved'), ('EXPENSE_REJECTED', 'Expense Rejected')], max_length=100),
        ),
    ]
