# Generated by Django 5.1.15 on 2026-07-13 13:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesMonthlyTarget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('segment', models.CharField(choices=[('TRADING', 'Trading'), ('SOLUTIONS', 'Solutions')], max_length=20)),
                ('order_booking_target', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('revenue_target', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('gross_margin_target', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('deals_won_target', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'sales_monthly_targets',
                'ordering': ['-year', '-month', 'segment'],
                'constraints': [models.UniqueConstraint(fields=('year', 'month', 'segment'), name='unique_sales_target_per_month_segment'), models.CheckConstraint(condition=models.Q(('month__gte', 1), ('month__lte', 12)), name='sales_target_month_range')],
            },
        ),
    ]
